--insert into persona(persona_nombre,persona_apellido,persona_email)values('susana','lara','slara@gmail.com')
--select * from persona
--update persona set persona_nombre='ivonne',persona_email='iesparsa@gmail.com'
--where persona_id=4
