# Generated by Django 3.2.6 on 2021-08-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_firstname', models.CharField(max_length=100)),
                ('person_lastname', models.CharField(max_length=100)),
                ('person_phone', models.CharField(max_length=10)),
                ('person_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=255)),
                ('user_active', models.BooleanField()),
                ('person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.person')),
            ],
        ),
    ]
